import image from "../assets/icons/Misc icon.svg";

export const quote = {
  rfgNo: "RFG-10234",
  title: "Request for Equipment",
  department: "Maternity",
  deliveryDate: "2024-08-13",
  items: [
    {
      name: "Oxygen concentration",
      id: "28373",
      variant: "Blue",
      quantity: 1,
      unit: "pieces",
      price: 200.0,
      amount: 2000.0,
      deliveryDate: "2024-07-02",
      image: image,
    },
    {
      name: "Mechanical ventilation",
      id: "28373",
      variant: "Red",
      quantity: 1,
      unit: "kg",
      price: 350.0,
      amount: 2500.0,
      deliveryDate: "2024-08-07",
      image: image,
    },
    {
      name: "Patient monitor",
      id: "28373",
      variant: "blue",
      quantity: 1,
      unit: "unit",
      price: 300.0,
      amount: 1500.0,
      deliveryDate: "2024-08-13",
      image: image,
    },
    {
      name: "Mechanical ventilation",
      id: "28373",
      variant: "Green",
      quantity: 1,
      unit: "unit",
      price: 200.0,
      amount: 1500.0,
      deliveryDate: "2024-09-08",
      image: image,
    },
  ],
};
